markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: arXiv Radar
description: An intelligent system that monitors and curates cutting-edge AI research papers from arXiv.
# baseurl: "/arXivRadar"
# url: "https://lixin97.github.io"

# Theme customization
github:
  is_project_page: false

# Paper List table (3 columns)
paper_list:
  columns: 3
  width: 100%
  th:first-child,
  td:first-child {
    width: 70%;
  }
  th:nth-child(2),
  td:nth-child(2) {
    width: 15%;
  }
  th:nth-child(3),
  td:nth-child(3) {
    width: 15%;
  }
