markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: arXiv Radar
description: An intelligent system that monitors and curates cutting-edge AI research papers from arXiv.
# baseurl: "/arXivRadar"
# url: "https://lixin97.github.io"

# Theme customization
github:
  is_project_page: false

# CSS customization
style: |
  .paper-list {
    width: 100%;
  }
  .paper-list th:first-child,
  .paper-list td:first-child {
    width: 70%;  /* Paper title & abstract column */
  }
  .paper-list th:nth-child(2),
  .paper-list td:nth-child(2) {
    width: 15%;  /* Date column */
  }
  .paper-list th:nth-child(3),
  .paper-list td:nth-child(3) {
    width: 15%;  /* Comment column */
  }