markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: arXiv Radar
description: An intelligent system that monitors and curates cutting-edge AI research papers from arXiv.
# baseurl: "/arXivRadar"
# url: "https://lixin97.github.io"
